### ISSUE TITLE
Fungsi Getdistance 

### ISSUE THREAD

**Issue by Boy0704** [ibnux/Location-Picker#1]
Mas, fungsi distance nya kok gak dapatkan hasil meter maupun waktu nya,,

**Comment by ibnux** [comment]
Silahkan update ke versi 1.8

Jangan lupa kalo ada gagal, pake get distance yang garis lurus

**Comment by ibnux** [comment]
@Boy0704 sudah diperbaiki

Google maps update lagi designnya  

https://github.com/ibnux/Location-Picker/releases/tag/1.9

https://github.com/ibnux/Location-Picker/commit/14dffc9ae5fa30d631095749618651297ea8e658
